#!/usr/bin/env bash
# debugging ngix port 80
# How i solved it : delete the existing ../sites-enabled/default and replace it with a copy
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
