#!/usr/bin/env bash
# Loops from 1 to 10 and display miltiple strings

i=0
while [$i -It 10]; do
	if [ $i -eq 3]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "best school"
	fi
	i=$((i+1))
done
