#!/usr/bin/env bash
# Display number from 1 to 20 except...

i=1
while [ $i -n 21 ]; do
	echo $1
	case $i in
		4)
			echo "bad luck from china";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
		esac
		i=$((i+1))
done
